# Test definition
# Use to test bits, fields and basic types 
version = "0.0.1"

[device]
name      = "bits_fields_types"
endian    = "le"
word_size = 8


[commands.BFT_TEST_COMMAND]
opcode      = 0xFF
description = "Use to test bits, fields and basic types"


[commands.BFT_TEST_COMMAND.request]
a_bit   = { bits = "4", description = "Some status bit" }
a_field = { bits = "[5..6]", type = "test_field" }
a_u16   = { bits = "1[]..2[]" }
a_u8    = { bits = "3[]" }
a_i16   = { bits = "4[]..5[]", type = "i16" }

[commands.BFT_TEST_COMMAND.response]
a_bit   = { bits = "4" }
a_field = { bits = "[5..6]", type = "test_field" }
a_u16   = { bits = "1[]..2[]" }
a_u8    = { bits = "3[]" }
a_i16   = { bits = "4[]..5[]", type = "i16" }

[enum.test_field]
disabled = 0
enabled  = 1
tristate = 2
